# Generated by Django 4.0.1 on 2022-03-18 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('year_of_experience', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('skill_level', models.IntegerField()),
                ('is_open', models.BooleanField(default=False)),
                ('number_of_applicants', models.IntegerField(default=0)),
                ('selected_applicants', models.IntegerField(default=0)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='base.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_experience', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('skill_level', models.IntegerField()),
                ('is_selected', models.BooleanField(default=False)),
                ('number_of_applicants', models.IntegerField(default=0)),
                ('selected_applicants', models.IntegerField(default=0)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='base.candidate')),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='base.recruiter_job')),
            ],
        ),
    ]
