# Generated by Django 4.0.1 on 2022-03-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_recruiter_job_candidate_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_applications',
            name='skill_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_applications',
            name='year_of_experience',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiter_job',
            name='skill_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiter_job',
            name='year_of_experience',
            field=models.CharField(max_length=50),
        ),
    ]
