# Generated by Django 4.0.1 on 2022-03-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_candidate_applications_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter_job',
            name='max_number_of_applicants',
            field=models.IntegerField(default=1),
        ),
    ]
